- name: confirm Tower version w/ check mode
  awx.awx.tower_organization:
    name: Default
  check_mode: yes
  register: result

- assert:
    that:
      - "result.tower_version is defined"

- name: Make sure the default Default organization exists
  awx.awx.tower_organization:
    name: Default
