---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - gce:
        instance_names: this-is-an-instance-created-by-tower-qa-tests  # should not match anything
        state: "{{ state | default('absent') }}"
