- name: Set the value of AWX_PROOT_SHOW_PATHS
  awx.awx.tower_settings:
    name: "AWX_PROOT_SHOW_PATHS"
    value:
      - '/var/lib/awx/projects/'
      - '/tmp'
  register: result

- assert:
    that:
      - "result is changed"

- name: Revert the value of AWX_PROOT_SHOW_PATHS to its default
  awx.awx.tower_settings:
    name: "AWX_PROOT_SHOW_PATHS"
    value: []
  register: result

- assert:
    that:
      - "result is changed"

- name: Set the value of AWX_PROOT_BASE_PATH
  awx.awx.tower_settings:
    name: AWX_PROOT_BASE_PATH
    value: "/tmp/newtmp"
  register: result

- assert:
    that:
      - "result.value == '/tmp/newtmp'"

- name: Revert the value of AWX_PROOT_BASE_PATH to its default
  awx.awx.tower_settings:
    name: AWX_PROOT_BASE_PATH
    value: "/tmp"
  register: result

- assert:
    that:
      - "result.value == '/tmp'"
